### ISSUE TITLE
Some help

### ISSUE THREAD

**Issue by RynFlutsch** [Theoi-Meteoroi/GPIO-pca9548#1]
Hey Theoi,

i tried all and nothing works.
Not the script and manual either.
After rebooting the config.txt lost the 2 added lines. 
sudo i2cdetect -F 3
Error: Could not open file `/dev/i2c-3' or `/dev/i2c/3': No such file or directory
It looks like only hardware i2c is working.

**Comment by Theoi-Meteoroi** [comment]
Howdy Ryn, You mention the lines in /boot/config.txt do not persist.  Do you have the output of the script from that run?  The script assumes you are logged in as user "pi" and that user "pi" can use the 'sudo' command to allow manipulation of those files.

What does the output of 'dmesg' look like after reboot?

**Comment by RynFlutsch** [comment]
dmesg show nothing with i2c.
I am Using dietpi based on raspbian lite.
Why Kyle removed the multiplexer support. It was so easy ... ;(
I edited the config.txt on the sd card, that helped:

root@BastelPi:~# sudo i2cdetect -F 3
Functionalities implemented by /dev/i2c-3:
I2C                              yes
SMBus Quick Command              yes
SMBus Send Byte                  yes
SMBus Receive Byte               yes
SMBus Write Byte                 yes
SMBus Read Byte                  yes
SMBus Write Word                 yes
SMBus Read Word                  yes
SMBus Process Call               yes
SMBus Block Write                yes
SMBus Block Read                 yes
SMBus Block Process Call         yes
SMBus PEC                        yes
I2C Block Write                  yes
I2C Block Read                   yes

Now i have to understand the resistor issue on multiplexers and how to add multiple AM2315 to it.

Because i have the normal TCA 9548a not the Gravity Multiplexer.

**Comment by Theoi-Meteoroi** [comment]
Sorry, I haven't tested the script on any other distro.   It looks like the gpio-i2c overlay is working.  The pull-up value can be 4.7k to 10k ohms. On the system side, pull up to 3.3v. 
I've used a number of different breakouts - the connections are all pretty similar except some need pull-ups on the reset line and pull-downs on the address lines.  
Let me know if you need more assistance.  

I did take a look at dietpi while I wrote this.  I haven't been able to figure out where they would keep the device-tree overlay database.  Looking at https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-software  I can see they have a method to 'inject' a dtoverlay for some functions.   The overlay should work fine once compiled and placed where the overlays are stored in DietPi.  Then adding the directive in the config.txt file should allow the kernel to see the mux and build I2C buses.

**Comment by Theoi-Meteoroi** [comment]
Closing stale issue.  Unknown OS support.
